[project]
name = "djgpt"
version = "0.1.0"
description = "Add a short description here"
authors = ["Matt Oates <mattoates+support@gmail.com>"]
channels = ["apple", "pytorch-nightly", "conda-forge"]
platforms = ["osx-arm64"]

[tasks]
start = "python cli.py"

[dependencies]
python = ">=3.11.8,<3.13"
typer = ">=0.9.0,<0.10"
spotipy = ">=2.23.0,<2.24"
pytorch = ">=2.3.0.dev20240311,<2.4.1"
python-dotenv = ">=1.0.1,<1.1"
speechrecognition = "==3.10.0"
pyobjc-core = ">=10.2,<11"
pyobjc-framework-coreservices = ">=9.1,<10"
strenum = ">=0.4.15,<0.5"
portaudio = ">=19.6.0,<19.7"

[pypi-dependencies]
openai = "==0.28"
openai-whisper = "*"
pyaudio = "*"
pyttsx3 = "*"
pocketsphinx = "*"
